modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"
[[mods]]
modId = "explodeblock"
version = "1.0"
displayName = "ExplodeBlock"
authors = "zcytxcbyz"
description = '''
Generate explosive stones in the world.
'''
[[dependencies.explodeblock]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.explodeblock]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
